Areas/Admin/Controllers/CategoriesController.cs
using RealEstate.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_CommerceWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly RealEstateContext con;

        public CategoriesController(RealEstateContext context) => con = context;
        List<TbCategory> lstCategories = new List<TbCategory>();
        TbCategory category = new TbCategory();
        public IActionResult Index()
        {
            lstCategories = con.TbCategories.Include(a => a.TbProducts).ToList();
            return View(lstCategories);
        }
        public IActionResult Create()
        {
            ViewBag.state = "New Category";
            ViewBag.enter = "Add";
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TbCategory Category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (Category.CategoryId == 0)
                        con.TbCategories.Add(Category);
                    else
                        con.Entry(Category).State = EntityState.Modified;
                    con.SaveChanges();
                    return RedirectToAction();
                }
                else
                    return View(Category);
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }
        public IActionResult Edit(int id)
        {
            ViewBag.state = "Edit Product";
            ViewBag.enter = "Edit";
            category = con.TbCategories.Find(id);
            return View("Create", category);
        }
        public IActionResult DeleteCategory(int id)
        {
            con.Remove(con.TbCategories.Find(id));
            con.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Controllers/ProductsController.cs
using RealEstate.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace E_CommerceWebSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly RealEstateContext context;
        public ProductsController(RealEstateContext context) => this.context = context;
        // GET: HomeController
        List<TbProduct> products = new List<TbProduct>();
        TbProduct product = new TbProduct();
        public IActionResult Index()
        {

            products = context.TbProducts.Include(a => a.Category).ToList();
            return View(products);
        }


        // GET: HomeController/Create
        public IActionResult Create()
        {
            ViewBag.state = "New Product";
            ViewBag.enter = "Add";
            ViewBag.Category = context.TbCategories.ToList();
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TbProduct Product, List<IFormFile> Files)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Files)
                {
                    if (file.Length > 0)
                    {
                        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                        using (var stream = System.IO.File.Create(filePaths))
                        {
                            await file.CopyToAsync(stream);
                        }
                        Product.ImageName = ImageName;
                    }
                }
                try
                {
                    if (Product.ProductId == 0)
                        context.TbProducts.Add(Product);
                    else
                    {
                        TbProduct p = new TbProduct();
                        p = context.TbProducts.ToList().FirstOrDefault(a => a.ProductId == Product.ProductId);
                        if (Product.ImageName == null)
                            p.ImageName = p.ImageName;
                        else
                            p.ImageName = Product.ImageName;
                        p.ProductName = Product.ProductName;
                        p.ProductBuyPrice = Product.ProductBuyPrice;
                        p.ProductSalePrice = Product.ProductSalePrice;
                        p.CategoryId = Product.CategoryId;

                        //context.Entry(Product).State = EntityState.Modified;
                    }
                    context.SaveChanges();
                    return RedirectToAction();
                }
                catch (Exception ex)
                {
                    ex.Message.ToString();
                    return View();
                }
            }
            else
            {
                try
                {
                    ViewBag.Category = context.TbCategories.ToList();
                    return View(Product);
                }

                catch (Exception ex)
                {
                    await Response.WriteAsync(ex.ToString());
                    return View();
                }
            }

        }

        // GET: HomeController/Edit/5
        TbProduct pp = new TbProduct();
        public IActionResult Edit(int id)
        {

            ViewBag.state = "Edit Product";
            ViewBag.enter = "Edit";
            ViewBag.Category = context.TbCategories.ToList();
            pp = context.TbProducts.Include(a => a.TbImages).ToList().FirstOrDefault(a => a.ProductId == id);
            return View("Create", pp);
        }


        public IActionResult DeleteProduct(int id)
        {
            try
            {
                product = context.TbProducts.Find(id);
                context.TbProducts.Remove(product);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Index");
            }
        }
    }
}

Areas/Admin/Views/Categories/Create.cshtml
@model TbCategory
<br />
<br />
<br />
<br />
<br />
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card card-info">
                    <div class="card-header">
                        <h3>@ViewBag.state</h3>
                        <a asp-controller="Products" asp-area="Admin" asp-action="Create" class="btn btn-primary" style="margin-left:83%">Add Product</a>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="post" role="form" enctype="multipart/form-data" class="form-horizontal">
                        <div class="card-body">
                            @if (ViewBag.state == "Edit Product")
                            {
                                <input type="hidden" asp-for="CategoryId" />
                            }
                            <div class="form-group row">
                                <label asp-for="CategoryName" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" asp-for="CategoryName" class="form-control" placeholder="Category Name">
                                    <span asp-validation-for="CategoryName"></span>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" asp-area="Admin" asp-controller="Categories" asp-action="Create" class="btn btn-info">@ViewBag.enter</button>
                            <a asp-action="Index" class="btn btn-primary" style="margin-left:78%">Back to List</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<br />
<br />
<br />
@section Scripts{
    <script src="~/adminpanel/dist/js/adminlte.js"></script>
    <script src="~/adminpanel/dist/js/adminlte.min.js"></script>
    <script src="~/adminpanel/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="~/adminpanel/plugins/jquery-validation/jquery.validate.min.js"></script>
}

Areas/Admin/Views/Categories/Index.cshtml
@model List<TbCategory>


@{
    ViewData["title"] = "Data";
}
@section styles{
    <link href="~/adminpanel/dist/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/adminpanel/dist/css/adminlte.css" rel="stylesheet" />
}
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <div>
                                <a class="btn btn-primary" asp-area="Admin" asp-controller="categories" asp-action="create">Add Category</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Category Name</th>
                                <th>Number of Products</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>@item.CategoryName</td>
                                <td>@item.TbProducts.Count</td>
                                <td>
                                    <a asp-route-id="@item.CategoryId" asp-action="Edit" class="btn btn-warning">Edit</a>
                                    <a asp-route-id="@item.CategoryId" asp-action="DeleteCategory" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>
<br />
<br />
<br />